package com.gg.springbootvuejs.base.entity;

public class UpmsUserRole {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column upms_user_role.user_role_id
     *
     * @mbg.generated Sat Apr 21 22:51:18 CST 2018
     */
    private Integer userRoleId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column upms_user_role.user_id
     *
     * @mbg.generated Sat Apr 21 22:51:18 CST 2018
     */
    private Integer userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column upms_user_role.role_id
     *
     * @mbg.generated Sat Apr 21 22:51:18 CST 2018
     */
    private Integer roleId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column upms_user_role.user_role_id
     *
     * @return the value of upms_user_role.user_role_id
     *
     * @mbg.generated Sat Apr 21 22:51:18 CST 2018
     */
    public Integer getUserRoleId() {
        return userRoleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column upms_user_role.user_role_id
     *
     * @param userRoleId the value for upms_user_role.user_role_id
     *
     * @mbg.generated Sat Apr 21 22:51:18 CST 2018
     */
    public void setUserRoleId(Integer userRoleId) {
        this.userRoleId = userRoleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column upms_user_role.user_id
     *
     * @return the value of upms_user_role.user_id
     *
     * @mbg.generated Sat Apr 21 22:51:18 CST 2018
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column upms_user_role.user_id
     *
     * @param userId the value for upms_user_role.user_id
     *
     * @mbg.generated Sat Apr 21 22:51:18 CST 2018
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column upms_user_role.role_id
     *
     * @return the value of upms_user_role.role_id
     *
     * @mbg.generated Sat Apr 21 22:51:18 CST 2018
     */
    public Integer getRoleId() {
        return roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column upms_user_role.role_id
     *
     * @param roleId the value for upms_user_role.role_id
     *
     * @mbg.generated Sat Apr 21 22:51:18 CST 2018
     */
    public void setRoleId(Integer roleId) {
        this.roleId = roleId;
    }
}