package com.gg.springbootvuejs.base.entity;

public class UpmsRolePermission {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column upms_role_permission.role_permission_id
     *
     * @mbg.generated Sat Apr 21 22:51:18 CST 2018
     */
    private Integer rolePermissionId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column upms_role_permission.role_id
     *
     * @mbg.generated Sat Apr 21 22:51:18 CST 2018
     */
    private Integer roleId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column upms_role_permission.permission_id
     *
     * @mbg.generated Sat Apr 21 22:51:18 CST 2018
     */
    private Integer permissionId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column upms_role_permission.role_permission_id
     *
     * @return the value of upms_role_permission.role_permission_id
     *
     * @mbg.generated Sat Apr 21 22:51:18 CST 2018
     */
    public Integer getRolePermissionId() {
        return rolePermissionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column upms_role_permission.role_permission_id
     *
     * @param rolePermissionId the value for upms_role_permission.role_permission_id
     *
     * @mbg.generated Sat Apr 21 22:51:18 CST 2018
     */
    public void setRolePermissionId(Integer rolePermissionId) {
        this.rolePermissionId = rolePermissionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column upms_role_permission.role_id
     *
     * @return the value of upms_role_permission.role_id
     *
     * @mbg.generated Sat Apr 21 22:51:18 CST 2018
     */
    public Integer getRoleId() {
        return roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column upms_role_permission.role_id
     *
     * @param roleId the value for upms_role_permission.role_id
     *
     * @mbg.generated Sat Apr 21 22:51:18 CST 2018
     */
    public void setRoleId(Integer roleId) {
        this.roleId = roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column upms_role_permission.permission_id
     *
     * @return the value of upms_role_permission.permission_id
     *
     * @mbg.generated Sat Apr 21 22:51:18 CST 2018
     */
    public Integer getPermissionId() {
        return permissionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column upms_role_permission.permission_id
     *
     * @param permissionId the value for upms_role_permission.permission_id
     *
     * @mbg.generated Sat Apr 21 22:51:18 CST 2018
     */
    public void setPermissionId(Integer permissionId) {
        this.permissionId = permissionId;
    }
}