package com.gg.springbootvuejs.base.entity;

import java.util.Date;

public class UpmsRole {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column upms_role.role_id
     *
     * @mbg.generated Sat Apr 21 22:51:18 CST 2018
     */
    private Integer roleId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column upms_role.name
     *
     * @mbg.generated Sat Apr 21 22:51:18 CST 2018
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column upms_role.title
     *
     * @mbg.generated Sat Apr 21 22:51:18 CST 2018
     */
    private String title;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column upms_role.description
     *
     * @mbg.generated Sat Apr 21 22:51:18 CST 2018
     */
    private String description;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column upms_role.version
     *
     * @mbg.generated Sat Apr 21 22:51:18 CST 2018
     */
    private Integer version;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column upms_role.created_by
     *
     * @mbg.generated Sat Apr 21 22:51:18 CST 2018
     */
    private String createdBy;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column upms_role.created_time
     *
     * @mbg.generated Sat Apr 21 22:51:18 CST 2018
     */
    private Date createdTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column upms_role.last_upd_by
     *
     * @mbg.generated Sat Apr 21 22:51:18 CST 2018
     */
    private String lastUpdBy;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column upms_role.last_upd_time
     *
     * @mbg.generated Sat Apr 21 22:51:18 CST 2018
     */
    private Date lastUpdTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column upms_role.role_id
     *
     * @return the value of upms_role.role_id
     *
     * @mbg.generated Sat Apr 21 22:51:18 CST 2018
     */
    public Integer getRoleId() {
        return roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column upms_role.role_id
     *
     * @param roleId the value for upms_role.role_id
     *
     * @mbg.generated Sat Apr 21 22:51:18 CST 2018
     */
    public void setRoleId(Integer roleId) {
        this.roleId = roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column upms_role.name
     *
     * @return the value of upms_role.name
     *
     * @mbg.generated Sat Apr 21 22:51:18 CST 2018
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column upms_role.name
     *
     * @param name the value for upms_role.name
     *
     * @mbg.generated Sat Apr 21 22:51:18 CST 2018
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column upms_role.title
     *
     * @return the value of upms_role.title
     *
     * @mbg.generated Sat Apr 21 22:51:18 CST 2018
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column upms_role.title
     *
     * @param title the value for upms_role.title
     *
     * @mbg.generated Sat Apr 21 22:51:18 CST 2018
     */
    public void setTitle(String title) {
        this.title = title == null ? null : title.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column upms_role.description
     *
     * @return the value of upms_role.description
     *
     * @mbg.generated Sat Apr 21 22:51:18 CST 2018
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column upms_role.description
     *
     * @param description the value for upms_role.description
     *
     * @mbg.generated Sat Apr 21 22:51:18 CST 2018
     */
    public void setDescription(String description) {
        this.description = description == null ? null : description.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column upms_role.version
     *
     * @return the value of upms_role.version
     *
     * @mbg.generated Sat Apr 21 22:51:18 CST 2018
     */
    public Integer getVersion() {
        return version;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column upms_role.version
     *
     * @param version the value for upms_role.version
     *
     * @mbg.generated Sat Apr 21 22:51:18 CST 2018
     */
    public void setVersion(Integer version) {
        this.version = version;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column upms_role.created_by
     *
     * @return the value of upms_role.created_by
     *
     * @mbg.generated Sat Apr 21 22:51:18 CST 2018
     */
    public String getCreatedBy() {
        return createdBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column upms_role.created_by
     *
     * @param createdBy the value for upms_role.created_by
     *
     * @mbg.generated Sat Apr 21 22:51:18 CST 2018
     */
    public void setCreatedBy(String createdBy) {
        this.createdBy = createdBy == null ? null : createdBy.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column upms_role.created_time
     *
     * @return the value of upms_role.created_time
     *
     * @mbg.generated Sat Apr 21 22:51:18 CST 2018
     */
    public Date getCreatedTime() {
        return createdTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column upms_role.created_time
     *
     * @param createdTime the value for upms_role.created_time
     *
     * @mbg.generated Sat Apr 21 22:51:18 CST 2018
     */
    public void setCreatedTime(Date createdTime) {
        this.createdTime = createdTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column upms_role.last_upd_by
     *
     * @return the value of upms_role.last_upd_by
     *
     * @mbg.generated Sat Apr 21 22:51:18 CST 2018
     */
    public String getLastUpdBy() {
        return lastUpdBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column upms_role.last_upd_by
     *
     * @param lastUpdBy the value for upms_role.last_upd_by
     *
     * @mbg.generated Sat Apr 21 22:51:18 CST 2018
     */
    public void setLastUpdBy(String lastUpdBy) {
        this.lastUpdBy = lastUpdBy == null ? null : lastUpdBy.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column upms_role.last_upd_time
     *
     * @return the value of upms_role.last_upd_time
     *
     * @mbg.generated Sat Apr 21 22:51:18 CST 2018
     */
    public Date getLastUpdTime() {
        return lastUpdTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column upms_role.last_upd_time
     *
     * @param lastUpdTime the value for upms_role.last_upd_time
     *
     * @mbg.generated Sat Apr 21 22:51:18 CST 2018
     */
    public void setLastUpdTime(Date lastUpdTime) {
        this.lastUpdTime = lastUpdTime;
    }
}