package com.gg.springbootvuejs.base.dao;

import com.gg.springbootvuejs.base.entity.UpmsUserRole;
import com.gg.springbootvuejs.base.entity.UpmsUserRoleExample;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface UpmsUserRoleMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table upms_user_role
     *
     * @mbg.generated Sat Apr 21 22:51:18 CST 2018
     */
    long countByExample(UpmsUserRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table upms_user_role
     *
     * @mbg.generated Sat Apr 21 22:51:18 CST 2018
     */
    int deleteByExample(UpmsUserRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table upms_user_role
     *
     * @mbg.generated Sat Apr 21 22:51:18 CST 2018
     */
    int deleteByPrimaryKey(Integer userRoleId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table upms_user_role
     *
     * @mbg.generated Sat Apr 21 22:51:18 CST 2018
     */
    int insert(UpmsUserRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table upms_user_role
     *
     * @mbg.generated Sat Apr 21 22:51:18 CST 2018
     */
    int insertSelective(UpmsUserRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table upms_user_role
     *
     * @mbg.generated Sat Apr 21 22:51:18 CST 2018
     */
    List<UpmsUserRole> selectByExample(UpmsUserRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table upms_user_role
     *
     * @mbg.generated Sat Apr 21 22:51:18 CST 2018
     */
    UpmsUserRole selectByPrimaryKey(Integer userRoleId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table upms_user_role
     *
     * @mbg.generated Sat Apr 21 22:51:18 CST 2018
     */
    int updateByExampleSelective(@Param("record") UpmsUserRole record, @Param("example") UpmsUserRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table upms_user_role
     *
     * @mbg.generated Sat Apr 21 22:51:18 CST 2018
     */
    int updateByExample(@Param("record") UpmsUserRole record, @Param("example") UpmsUserRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table upms_user_role
     *
     * @mbg.generated Sat Apr 21 22:51:18 CST 2018
     */
    int updateByPrimaryKeySelective(UpmsUserRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table upms_user_role
     *
     * @mbg.generated Sat Apr 21 22:51:18 CST 2018
     */
    int updateByPrimaryKey(UpmsUserRole record);
}