package com.gg.springbootvuejs.base.dao;

import com.gg.springbootvuejs.base.entity.UpmsPermission;
import com.gg.springbootvuejs.base.entity.UpmsPermissionExample;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface UpmsPermissionMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table upms_permission
     *
     * @mbg.generated Sat Apr 21 22:51:18 CST 2018
     */
    long countByExample(UpmsPermissionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table upms_permission
     *
     * @mbg.generated Sat Apr 21 22:51:18 CST 2018
     */
    int deleteByExample(UpmsPermissionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table upms_permission
     *
     * @mbg.generated Sat Apr 21 22:51:18 CST 2018
     */
    int deleteByPrimaryKey(Integer permissionId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table upms_permission
     *
     * @mbg.generated Sat Apr 21 22:51:18 CST 2018
     */
    int insert(UpmsPermission record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table upms_permission
     *
     * @mbg.generated Sat Apr 21 22:51:18 CST 2018
     */
    int insertSelective(UpmsPermission record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table upms_permission
     *
     * @mbg.generated Sat Apr 21 22:51:18 CST 2018
     */
    List<UpmsPermission> selectByExample(UpmsPermissionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table upms_permission
     *
     * @mbg.generated Sat Apr 21 22:51:18 CST 2018
     */
    UpmsPermission selectByPrimaryKey(Integer permissionId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table upms_permission
     *
     * @mbg.generated Sat Apr 21 22:51:18 CST 2018
     */
    int updateByExampleSelective(@Param("record") UpmsPermission record, @Param("example") UpmsPermissionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table upms_permission
     *
     * @mbg.generated Sat Apr 21 22:51:18 CST 2018
     */
    int updateByExample(@Param("record") UpmsPermission record, @Param("example") UpmsPermissionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table upms_permission
     *
     * @mbg.generated Sat Apr 21 22:51:18 CST 2018
     */
    int updateByPrimaryKeySelective(UpmsPermission record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table upms_permission
     *
     * @mbg.generated Sat Apr 21 22:51:18 CST 2018
     */
    int updateByPrimaryKey(UpmsPermission record);
}