package com.gg.springbootvuejs.base.dao;

import com.gg.springbootvuejs.base.entity.UpmsUser;
import com.gg.springbootvuejs.base.entity.UpmsUserExample;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface UpmsUserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table upms_user
     *
     * @mbg.generated Sat Apr 21 22:51:18 CST 2018
     */
    long countByExample(UpmsUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table upms_user
     *
     * @mbg.generated Sat Apr 21 22:51:18 CST 2018
     */
    int deleteByExample(UpmsUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table upms_user
     *
     * @mbg.generated Sat Apr 21 22:51:18 CST 2018
     */
    int deleteByPrimaryKey(Integer userId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table upms_user
     *
     * @mbg.generated Sat Apr 21 22:51:18 CST 2018
     */
    int insert(UpmsUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table upms_user
     *
     * @mbg.generated Sat Apr 21 22:51:18 CST 2018
     */
    int insertSelective(UpmsUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table upms_user
     *
     * @mbg.generated Sat Apr 21 22:51:18 CST 2018
     */
    List<UpmsUser> selectByExample(UpmsUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table upms_user
     *
     * @mbg.generated Sat Apr 21 22:51:18 CST 2018
     */
    UpmsUser selectByPrimaryKey(Integer userId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table upms_user
     *
     * @mbg.generated Sat Apr 21 22:51:18 CST 2018
     */
    int updateByExampleSelective(@Param("record") UpmsUser record, @Param("example") UpmsUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table upms_user
     *
     * @mbg.generated Sat Apr 21 22:51:18 CST 2018
     */
    int updateByExample(@Param("record") UpmsUser record, @Param("example") UpmsUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table upms_user
     *
     * @mbg.generated Sat Apr 21 22:51:18 CST 2018
     */
    int updateByPrimaryKeySelective(UpmsUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table upms_user
     *
     * @mbg.generated Sat Apr 21 22:51:18 CST 2018
     */
    int updateByPrimaryKey(UpmsUser record);
}